/* eslint-disable import/no-anonymous-default-export */
export default {
    SET_MASTER_DATA: "SET_MASTER_DATA",
    GET_LOCATION_LIST: "GET_LOCATION_LIST",
    SELECTED_LOCATION: "SELECTED_LOCATION",
    RESET_SELECTED_LOCATION: "RESET_SELECTED_LOCATION",
    GET_BRANCH_LIST: "GET_BRANCH_LIST",
    SELECTED_BRANCH: "SELECTED_BRANCH",
    RESET_SELECTED_BRANCH: "RESET_SELECTED_BRANCH",
    GET_CATEGORY_LIST: "GET_CATEGORY_LIST",
    SELECTED_CATEGORY: "SELECTED_CATEGORY",
    RESET_SELECTED_CATEGORY: "RESET_SELECTED_CATEGORY",
    GET_SUB_CATEGORY_LIST: "GET_SUB_CATEGORY_LIST",
    SELECTED_SUB_CATEGORY: "SELECTED_SUB_CATEGORY",
    RESET_SELECTED_SUB_CATEGORY: "RESET_SELECTED_SUB_CATEGORY",
}